require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '16.0'

target 'myviroapp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
	pod 'ViroReact', :path => '../node_modules/@viro-community/react-viro/ios/'
	pod 'ViroKit', :path => '../node_modules/@viro-community/react-viro/ios/dist/ViroRenderer/'

  target 'myviroappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
		 # Reconfigure the pods to match the iOS version we're targetting
		installer.pods_project.targets.each do |target|
			target.build_configurations.each do |config|
				case target.name
				when 'RCT-Folly'
					config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
				else
					config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET')
				end
			end
		end
  end
end
